### ISSUE TITLE
Consider joining forces with Backdrop CMS?

### ISSUE THREAD

**Issue by klonos** [geru/yad7#1]
Hello @geru 👋🏼  ...one of our community members has noticed your project, and we were wondering if you'd be interested to join us in our efforts to provide continuity to Drupal 7.

In case you are not aware, Backdrop CMS has been around as a fork of Drupal since 2015. Please see our website for more information:
- https://backdropcms.org/philosophy
- https://backdropcms.org/why-fork-drupal
- https://backdropcms.org/leadership
- https://backdropcms.org/roadmap

Feel free to join our community discussions at https://backdrop.zulipchat.com or drop in during one of our weekly dev meetings: https://www.starts-at.com/event/4695504400

Cheers

**Comment by geru** [comment]
Hi @klonos thanks for reaching out. I am aware of Backdrop CMS and have worked to ensure Backdrop compatibility with my work. In the end, Backdrop is not a plug-and-play Drupal-7 replacement whereas YAD7 is. Also, Backdrop seems beholden to: CTools, Bootstrap, and JSON configuration, which all run contrary to my philosophy. Perhaps, you would like to participate in developing and supporting YAD7. It would be nice to have some collaboration. I have written a killer module (Y), which is much cleaner than CTools, and which can be used for a multitude of functionality including CSS preprocessing, plugin development, and templating. I never published my current Y Version 2 because I don't see any outside interest. Ultimately, I think Y should be **the** primary Drupal-development mechanism (strong words, I know). Stay in touch, --Hugh
